import { test, describe } from "node:test";
import assert from "node:assert/strict";
import { isAgentIdentity, isMessageCommand, isMessagePath, stripAttribution } from "./attribution.ts";

/** Real lines from GitHub commits / PR bodies (`gh search`), ids shortened. */
const AGENT_LINES = [
	// Claude Code
	"\u{1F916} Generated with [Claude Code](https://claude.com/claude-code)",
	"\u{1F916} Generated with [Claude Code](https://claude.ai/code)",
	"Co-Authored-By: Claude <noreply@anthropic.com>",
	"Co-Authored-By: Claude Opus 5.5 (1M context) <noreply@anthropic.com>",
	"Co-authored-by: Anthropic Claude <claude-ai@users.noreply.github.com>",
	"Assisted-by: Claude Opus 5",
	// OpenAI Codex
	"Co-authored-by: codex <codex@openai.com>",
	"Co-authored-by: codex <noreply@openai.com>",
	"Co-Authored-By: GPT Codex (gpt-6-sol) <codex@openai.com>",
	"Co-authored-by: codex <codex@users.noreply.github.com>",
	"Committed-By-Agent: codex",
	"\u{1F916} Generated with OpenAI Codex",
	"\u{1F916} Generated with [Codex](https://github.com/openai/codex)",
	"Generated with Codex (https://openai.com/codex)",
	"Generated-by: OpenAI Codex",
	"Generated-by: Codex (gpt-5.6-sol)",
	"Assisted-by: GPT-5.5",
	"https://chatgpt.com/codex/tasks/task_e_68a1b2c3",
	// Cursor
	"Co-authored-by: Cursor <cursoragent@cursor.com>",
	"Co-Authored-By: Cursor Agent <noreply@cursor.com>",
	"Signed-off-by: Cursor <cursoragent@cursor.com>",
	"Assisted-by: Cursor",
	"This pull request contains changes generated by a Cursor Cloud Agent",
	'<div><a href="https://cursor.com/agents/bc-1234?cursor_ref=pr_footer&cursor_cta=open_in_web"><picture><source srcset="https://cursor.com/x.svg"><img alt="Open in Web"></picture></a></div>',
	// GitHub Copilot
	"Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>",
	"Co-authored-by: Copilot Autofix powered by AI <62310815+Copilot@users.noreply.github.com>",
	"Copilot-Session: 3f2a1b4c-eb60-476d-a816-1234567890ab",
	// Devin
	"Co-Authored-By: Devin AI <158243242+devin-ai-integration[bot]@users.noreply.github.com>",
	"Co-Authored-By: Devin <1+staging-devin-ai-integration[bot]@users.noreply.github.com>",
	"Generated with [Devin](https://devin.ai)",
	"Devin Session: https://app.devin.ai/sessions/abc123",
	"Link to Devin session: https://app.devin.ai/sessions/abc123",
	"Open in Devin Desktop: https://app.devin.ai/desktop/session/abc?variant=devin",
	// Amp
	"Co-authored-by: Amp <amp@ampcode.com>",
	"Co-authored-by: Amp",
	"Amp-Thread-ID: https://ampcode.com/threads/T-0199-04ec-7681",
	"Generated with Amp",
	// OpenCode, Crush, aider
	"\u{1F916} Generated with [OpenCode](https://opencode.ai) (model: openai/gpt-5.6-sol)",
	"Generated with opencode (opencode/big-pickle).",
	"Co-Authored-By: opencode - deepseek-v4.1-flash (high) <noreply@opencode.ai>",
	"\u{1F498} Generated with Crush",
	"Assisted-by: Crush:grok-4.6",
	"Assisted-by: GLM-5.1 via Crush <crush@charm.land>",
	"Co-authored-by: aider (o4-mini) <noreply@aider.chat>",
	"Co-Authored-By: Aider+Gemini2.5Flash <noreply@aider.chat>",
	// Google: Gemini, Antigravity, Jules
	"Co-authored-by: Google Gemini <gemini-ai@users.noreply.github.com>",
	"Co-authored-by: Gemini <gemini@google.com>",
	"Co-authored-by: Antigravity (3.1 Pro) <gemini@google.com>",
	"Co-Authored-By: Agy (Gemini) <noreply@antigravity.dev>",
	"Co-authored-by: gemini-code-assist[bot] <176961590+gemini-code-assist[bot]@users.noreply.github.com>",
	"Co-authored-by: google-labs-jules[bot] <161369871+google-labs-jules[bot]@users.noreply.github.com>",
	"*PR created automatically by Jules for task [123](https://jules.google.com/task/123) started by @someone*",
	"**Session**: https://jules.google.com/session/456",
	// Others
	"Co-authored-by: factory-droid[bot] <138933559+factory-droid[bot]@users.noreply.github.com>",
	"Co-authored-by: Qwen-Coder <qwen-coder@alibabacloud.com>",
	"Co-Authored-By: Kiro <noreply@kiro.dev>",
	"Co-authored-by: Junie <junie@jetbrains.com>",
	"Co-authored-by: Jetbrains Junie",
	"Co-authored-by: Junie The Developer <junie-live-agent@users.noreply.github.com>",
	"\u{1F916} Generated with Codebuff",
	"Co-Authored-By: Codebuff <noreply@codebuff.com>",
	"Generated by Mistral Vibe.",
	"Co-Authored-By: Mistral Vibe <vibe@mistral.ai>",
	"Co-authored-by: Gitar <noreply@gitar.ai>",
	"Assisted-by: pi:llama.cpp/DeepSeek-V4-Flash-Vision-Exp",
];

/** Lines that look similar but belong to humans / ordinary tooling. */
const HUMAN_LINES = [
	"Co-authored-by: Jane Doe <jane@example.com>",
	"Co-authored-by: Jane Doe <jane@openai.com>",
	"Co-authored-by: Shaojin Wen <shaojin.wensj@alibaba-inc.com>",
	"Co-authored-by: Claude Monet <claude@monet.fr>",
	"Co-authored-by: Claude Dupont <12345+cdupont@users.noreply.github.com>",
	"Co-authored-by: starofgodmayomi-droid <1+starofgodmayomi-droid@users.noreply.github.com>",
	"Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>",
	"Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>",
	"Signed-off-by: Salman Mohammed <smohammed@squareup.com>",
	"Translate-URL: https://hosted.weblate.org/projects/f-droid/f-droid/uk/",
	"Change-Id: I1234567890abcdef",
	"Reviewed-by: Dom <d@example.com>",
	"docs: note this was generated with Claude's help",
	"Generated with Claude Code-style prompts in mind",
	"feat: support files generated by Cursor",
	"feat: add Claude provider",
	"Supports Claude Opus and GPT-5.",
	"* chore(schema): format generated config schema",
	"Charts are generated by running: make charts",
	"See the Codex docs at https://github.com/openai/codex",
];

const wrap = (line: string) => `fix: handle null\n\nLonger body.\n\n${line}`;

describe("stripAttribution: real agent lines are removed", () => {
	for (const line of AGENT_LINES) {
		test(line.slice(0, 90), () => {
			const r = stripAttribution(wrap(line));
			assert.equal(r.text, "fix: handle null\n\nLonger body.");
			assert.equal(r.count, 1);
		});
	}
});

describe("stripAttribution: human / ordinary lines are kept", () => {
	for (const line of HUMAN_LINES) {
		test(line.slice(0, 90), () => {
			assert.equal(stripAttribution(wrap(line)).text, wrap(line));
		});
	}
});

describe("stripAttribution: shell quoting", () => {
	test("heredoc commit: stacked trailers and blank lines all go, human kept", () => {
		const cmd = [
			`git commit -m "$(cat <<'EOF'`,
			"fix: handle null",
			"",
			"Here's why: the parser didn't check.",
			"",
			"\u{1F916} Generated with [Claude Code](https://claude.com/claude-code)",
			"",
			"Co-authored-by: Jane <jane@example.com>",
			"Co-Authored-By: Claude <noreply@anthropic.com>",
			"EOF",
			`)"`,
		].join("\n");
		const r = stripAttribution(cmd);
		assert.equal(
			r.text,
			// The blank line before Jane's trailer survives, so git still parses
			// it as a trailer block.
			`git commit -m "$(cat <<'EOF'\nfix: handle null\n\nHere's why: the parser didn't check.\n\nCo-authored-by: Jane <jane@example.com>\nEOF\n)"`,
		);
		assert.equal(r.count, 2);
	});

	test("trailer right before the closing quote", () => {
		assert.equal(
			stripAttribution(`git commit -m "fix: x\n\nCo-authored-by: Cursor <cursoragent@cursor.com>" && git push`).text,
			`git commit -m "fix: x" && git push`,
		);
	});

	test("separate -m argument becomes an empty -m (git ignores it)", () => {
		assert.equal(
			stripAttribution(`git commit -m "fix: x" -m "Co-authored-by: Amp <amp@ampcode.com>"`).text,
			`git commit -m "fix: x" -m ""`,
		);
	});

	test("literal \\n escapes (gh api JSON body)", () => {
		assert.equal(
			stripAttribution(`gh api repos/o/r/pulls -f body='Summary\\n\\nGenerated with Codex'`).text,
			`gh api repos/o/r/pulls -f body='Summary'`,
		);
	});

	test("an apostrophe is not an opening quote", () => {
		const s = "Here's the Devin session: https://app.devin.ai/sessions/x";
		assert.equal(stripAttribution(`body\n${s}`).text, `body\n${s}`);
	});

	test("an apostrophe after a tool name is not a closing quote", () => {
		const s = "Generated with Claude Code's help";
		assert.equal(stripAttribution(`body\n${s}`).text, `body\n${s}`);
	});

	test("keeps later non-agent trailers", () => {
		assert.equal(
			stripAttribution("fix\n\nCo-authored-by: Kiro <noreply@kiro.dev>\nSigned-off-by: Dom <d@x.com>").text,
			"fix\nSigned-off-by: Dom <d@x.com>",
		);
	});

	test("idempotent", () => {
		const once = stripAttribution(wrap(AGENT_LINES[0]));
		assert.equal(stripAttribution(once.text).count, 0);
	});
});

describe("isAgentIdentity", () => {
	test("bare names and Name:model", () => {
		for (const v of ["Claude", "Codex (gpt-5)", "Crush:grok-4.6", "Jetbrains Junie", "copilot-swe-agent[bot]"]) {
			assert.ok(isAgentIdentity(v), v);
		}
		for (const v of ["Jane Doe", "Claudette", "github-actions[bot]"]) {
			assert.ok(!isAgentIdentity(v), v);
		}
	});
});

describe("isMessageCommand", () => {
	test("matches message-carrying commands", () => {
		for (const c of [
			'git commit -m "x"',
			"git -C repo commit -F /tmp/m",
			"cd a && git tag -a v1 -m x",
			"gh pr create --title t --body b",
			"gh issue comment 3 -b hi",
			"gh release create v1 --notes x",
			"gh api repos/o/r/issues -f body=x",
			"glab mr create -d x",
			'jj describe -m "x"',
			'hg commit -m "x"',
		]) {
			assert.ok(isMessageCommand(c), c);
		}
	});

	test("ignores everything else", () => {
		for (const c of ["git status", "git log --grep Claude", "rg Co-Authored-By", "gh repo view", "echo commit"]) {
			assert.ok(!isMessageCommand(c), c);
		}
	});
});

describe("isMessagePath", () => {
	test("temp dirs and git message files", () => {
		assert.ok(isMessagePath("/tmp/pr-body.md"));
		assert.ok(isMessagePath("/var/folders/ab/T/msg.txt"));
		assert.ok(isMessagePath("/custom/tmp/x.md", "/custom/tmp"));
		assert.ok(isMessagePath("/repo/.git/COMMIT_EDITMSG"));
	});

	test("project files are not", () => {
		assert.ok(!isMessagePath("/Users/d/repo/README.md"));
		assert.ok(!isMessagePath("tmp/relative.md"));
		assert.ok(!isMessagePath("/repo/.git/config"));
	});
});
